SELECT DISTINCT sex FROM emp;
SELECT DISTINCT deptId FROM emp;
SELECT 2+3-4;
SELECT ename,salary*12 FROM emp;
SELECT ename,(salary+500)*12+5000 年薪 FROM emp;
SELECT * FROM dept ORDER BY did ASC;
SELECT * FROM dept ORDER BY did DESC;
SELECT * FROM emp ORDER BY salary DESC;
SELECT * FROM emp ORDER BY birthday DESC;
SELECT * FROM emp ORDER BY ename;
SELECT * FROM emp ORDER BY salary DESC,ename ASC;
SELECT * FROM emp ORDER BY sex,birthday DESC;
SELECT * FROM emp WHERE eid=5;
SELECT eid 编号,salary 工资,ename 姓名,birthday 生日 FROM emp WHERE ename="king";
SELECT * FROM emp WHERE deptId=20;
SELECT * FROM emp WHERE salary>=6000;
SELECT * FROM emp WHERE birthday>='1993-1-1';
SELECT * FROM emp WHERE deptId!=10;
SELECT * FROM emp WHERE deptId IS NULL;
SELECT * FROM emp WHERE deptId IS NOT NULL;
SELECT * FROM emp WHERE salary >=6000 AND sex = 1;
SELECT * FROM emp WHERE salary >=7000 AND salary <=10000;
SELECT * FROM emp WHERE salary NOT BETWEEN 7000 AND 10000;
SELECT * FROM emp WHERE salary<7000 OR salary>10000;
SELECT * FROM emp WHERE birthday<'1990-1-1' OR birthday>'1995-12-31';
SELECT * FROM emp WHERE deptId=20 OR deptId=30;
SELECT * FROM emp WHERE deptId!=20 AND deptId!=30;
SELECT * FROM emp WHERE deptId IN(20,30);
SELECT * FROM emp WHERE deptId	NOT IN(20,30);
SELECT * FROM emp LIMIT 0,5;
SELECT * FROM emp LIMIT 0,6;
SELECT * FROM emp LIMIT 6,6;
SELECT * FROM emp LIMIT 12,6;
