SELECT * FROM emp WHERE ename LIKE '%e%';
SELECT * FROM emp WHERE ename LIKE '%e_';
SELECT * FROM emp WHERE ename LIKE '%e';
SELECT COUNT(*) FROM emp;
SELECT COUNT(ename) FROM emp;
SELECT COUNT(deptId) FROM emp;
SELECT COUNT(*) FROM emp WHERE sex=1;
SELECT SUM(salary) FROM emp;
SELECT AVG(salary) FROM emp;
SELECT MAX(salary) FROM emp WHERE sex=1;
SELECT min(birthday) FROM emp;
SELECT sex,AVG(salary),MAX(salary) FROM emp GROUP BY sex;
SELECT deptId,COUNT(*),MAX(salary),MIN(salary) FROM emp GROUP BY deptId;
SELECT * FROM emp WHERE YEAR(birthday)=1993;
SELECT * FROM emp WHERE MONTH(birthday)=5;
SELECT did FROM dept WHERE dname='研发部';
SELECT * FROM emp WHERE deptId=(SELECT did FROM dept WHERE dname='研发部');
SELECT * FROM emp WHERE salary>(SELECT salary FROM emp WHERE ename='tom');
SELECT * FROM emp WHERE YEAR(birthday)=(SELECT YEAR(birthday) FROM emp WHERE ename='tom');
SELECT ename,dname FROM emp,dept WHERE deptId=did;
SELECT ename,dname FROM emp INNER JOIN dept ON deptId=did;
SELECT ename,dname FROM emp LEFT OUTER JOIN dept ON deptId=did;
SELECT ename,dname FROM emp RIGHT OUTER JOIN dept ON deptId=did;
(SELECT ename,dname FROM emp LEFT OUTER JOIN dept ON deptId=did) UNION ALL (SELECT ename,dname FROM emp RIGHT OUTER JOIN dept ON deptId=did);
SELECT * FROM emp WHERE sex=1 ORDER BY salary DESC LIMIT 0,3;