const http=require('http');
/*http.get('http://www.codeboy.com',function(res){
	//console.log(res.statusCode);
	res.on('data',function(buf){
		console.log(buf.toString());
	})
})
*/
/*http.get('http://www.tmooc.cn',function(res){
	res.on('data',function(buf){
		console.log(buf.toString());
	})
})
*/
http.get('',function(res){
	res.on('data',function(buf){
		console.log(buf);
	})
})