var emps=['tom','jerry','kate'];
// console.log(emps);
var products=['裤子','袜子','衬衫','羽绒服','鞋子'];
var citys=['北京','上海','深圳','广州'];
// console.log(products);
citys[2]='米兰';
citys[5]='巴黎';
// console.log(citys);
var car=new Array('奔驰','宝马','奥迪');
// console.log(car);
var car2=new Array(3);
car2[0]='凯迪拉克';
car2[1]='沃尔沃';
car2[2]='捷豹';
car2[3]='路虎';
// console.log(car2);
var course=['english','chinese','math'];
var arr=new Array(5);
arr[0]='前锋';
arr[1]='中锋';
arr[2]='后卫';
arr[3]='左卫';
arr[4]='右卫';
arr[arr.length]='普通后卫';
console.log(course);
console.log(arr.length);
